### ISSUE TITLE
It doesn't appear to work in on-page-edit mode

### ISSUE THREAD

**Issue by AThraen** [chrno1209/episerver-aceeditor#12]
When I try to edit a property in on-page-edit mode, it shows regular string editing - but that doesn't even seem to work.

**Comment by OMGPizzaGuy** [comment]
Confirming I can also see this problem in CMS 12.
The issue appears to be occuring around aceEditor.js line 209.
I am attempting to investigate, but would welcome the help of anyone more adept with dojo
