### ISSUE TITLE
Nuget package is missing the AceEditor.zip

### ISSUE THREAD

**Issue by anderstoft** [chrno1209/episerver-aceeditor#13]
When using the generated nuget package, the AceEditor.zip is not included in the modules folder.

It looks like the csproj file needs to include PackageCopyToOutput=true and that the Reference to AceEditor.targets is not correct

**Comment by OMGPizzaGuy** [comment]
Confirming I can also see this problem in CMS 12.
The issue appears to be occuring around aceEditor.js line 209.
I am attempting to investigate, but would welcome the help of anyone more adept with dojo

**Comment by OMGPizzaGuy** [comment]
I'll have (yet another) release including this change soon. Thank you!
