### ISSUE TITLE
Doesn't work on other admin urls than /EPiServer/

### ISSUE THREAD

**Issue by AThraen** [chrno1209/episerver-aceeditor#16]
When a site is configured to another admin url than /EPiServer/ the editor does not work as the js file referes to dependencies using a url containing /EPiServer/.

**Comment by OMGPizzaGuy** [comment]
I believe this should be fixed with version 12.2.2, which should be available on the Optimizely nuget feed soon.
If you have further issue, please let us know. Thanks!
