### ISSUE TITLE
Episerver v11 upgrade

### ISSUE THREAD

**Issue by davidknipe** [chrno1209/episerver-aceeditor#2]
Hi I have a version of this thats been upgraded to v11. Can you add me as a collaborator so I can send the pull request?

**Comment by chrno1209** [comment]
Yes sure David, thanks for collaborating on this repo :)

**Comment by chrno1209** [comment]
I've changed notification on Github to my personal email so I can check it everyday to make sure I will not miss any email from Github for any type of request like this.
So sorry to make you wait so long :)

**Comment by davidknipe** [comment]
Thanks for adding me! Sent you a pull request for the v11 branch now. Once its merged I will push a new version of the package to the Episerver Nuget feed
