### ISSUE TITLE
Support for XhtmlString?

### ISSUE THREAD

**Issue by OMGPizzaGuy** [chrno1209/episerver-aceeditor#6]
I made a an empty extension of your HtmlEditorDescriptor to register it for an XhtmlString, and that appears to work correctly. It also allows PropertyFor on the view to work. 
```
[EditorDescriptorRegistration(
    TargetType = typeof(XhtmlString),
    UIHint = AceEditor.UIHints.Html,
    EditorDescriptorBehavior = EditorDescriptorBehavior.PlaceLast)]
public class HtmlEditorDescriptor : AceEditor.Editors.HtmlEditorDescriptor {  }
```
Is there any reason I should not be doing this?
Does this make sense to integrate into your library?

**Comment by chrno1209** [comment]
Hi,
I think it should work fine :).
Do you consider a PR?

**Comment by OMGPizzaGuy** [comment]
Sure I'll look into submitting a PR soon!

**Comment by OMGPizzaGuy** [comment]
Pull Request created and tested in my project. Closing issue and continuing conversation on PR
